import { GoogleGenAI, Modality, Type } from '@google/genai';

function getMimeType(base64: string): string {
    return base64.substring(base64.indexOf(':') + 1, base64.indexOf(';'));
}

function base64ToPart(base64: string) {
    return {
        inlineData: {
            data: base64.split(',')[1],
            mimeType: getMimeType(base64),
        },
    };
}

export async function addWatermark(base64Image: string): Promise<string> {
    return new Promise((resolve, reject) => {
        const img = new Image();
        img.onload = () => {
            const canvas = document.createElement('canvas');
            const ctx = canvas.getContext('2d');
            if (!ctx) {
                return reject(new Error('Could not get canvas context'));
            }

            canvas.width = img.width;
            canvas.height = img.height;

            ctx.drawImage(img, 0, 0);

            // Watermark styling
            ctx.font = `bold ${Math.max(32, canvas.width / 20)}px Arial`;
            ctx.fillStyle = 'rgba(255, 255, 255, 0.4)';
            ctx.textAlign = 'center';
            ctx.textBaseline = 'middle';

            const text = 'Pet PawtrAI';
            const centerX = canvas.width / 2;
            const centerY = canvas.height / 2;
            
            ctx.save();
            ctx.translate(centerX, centerY);
            ctx.rotate(-0.35); // ~20 degrees
            ctx.fillText(text, 0, 0);
            ctx.restore();

            // Using JPEG with quality 0.9 to slightly reduce quality for the preview
            resolve(canvas.toDataURL('image/jpeg', 0.9));
        };
        img.onerror = () => {
            reject(new Error('Failed to load image for watermarking'));
        };
        img.src = base64Image;
    });
}

export async function upscaleImage(base64Image: string): Promise<string> {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                base64ToPart(base64Image),
                {
                    text: 'Upscale this image to a high resolution (e.g., 4x) suitable for printing on merchandise. It is critical to preserve all details, textures, and the artistic style of the original image without adding or removing any elements. Enhance clarity and sharpness for a print-quality result.',
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error('No upscaled image was generated by the API.');
}


export async function generatePetPortrait(base64Image: string, prompt: string): Promise<string> {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                base64ToPart(base64Image),
                {
                    text: prompt,
                },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }

    throw new Error('No image was generated by the API.');
}

export async function rateImageLikeness(originalBase64: string, generatedBase64: string): Promise<number> {
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
    
    const prompt = 'You are an expert art critic specializing in pet portraits. You will be given two images. The first is the original photo of a pet. The second is a generated portrait. Your task is to rate how well the generated portrait preserves the unique features, fur color and patterns, eye shape and color, and overall likeness of the pet from the original photo. On a scale of 0.0 to 1.0, where 1.0 is a perfect match and 0.0 is completely different, provide a likeness score. Respond ONLY with a single, valid JSON object in the format: {"likeness_score": <number>}. Do not include any other text, explanations, or markdown formatting.';

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: {
            parts: [
                base64ToPart(originalBase64),
                base64ToPart(generatedBase64),
                { text: prompt }
            ]
        },
        config: {
            responseMimeType: 'application/json',
            responseSchema: {
                type: Type.OBJECT,
                properties: {
                    likeness_score: {
                        type: Type.NUMBER,
                        description: 'A likeness score between 0.0 and 1.0'
                    }
                },
                required: ['likeness_score'],
            }
        }
    });

    try {
        const jsonText = response.text.trim();
        const result = JSON.parse(jsonText);
        if (typeof result.likeness_score === 'number' && result.likeness_score >= 0 && result.likeness_score <= 1) {
            return result.likeness_score;
        } else {
            throw new Error('Invalid likeness_score format or value in response.');
        }
    } catch (e) {
        console.error('Failed to parse likeness score from Gemini response:', response.text, e);
        // Fallback to 0 if parsing fails, forcing a retry
        return 0;
    }
}